# Generated by Django 4.1.3 on 2023-05-30 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("numberClickSucces", models.IntegerField()),
                ("numberClickTotal", models.IntegerField()),
                ("numberWins", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stadistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.game"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="user",
        ),
    ]
