# Generated by Django 4.1.3 on 2023-05-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_game_stadistics_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("surname", models.CharField(max_length=255, verbose_name="surname")),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField(blank=True, null=True)),
                ("birthday", models.DateField()),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
        ),
    ]
