# Generated by Django 4.1.3 on 2023-05-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_stadistics_estadistics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="user",
        ),
        migrations.DeleteModel(
            name="Estadistics",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
    ]
